# Install Tensorflow
RUN mamba install --quiet --yes \
    "tensorflow=${TENSORFLOW_VERSION}" && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
